# Generated by Django 6.1.1 on 2026-09-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_ts', models.DateTimeField(auto_now_add=True)),
                ('system_key', models.CharField(blank=True, default='', max_length=20)),
                ('action', models.CharField(max_length=40)),
                ('detail', models.CharField(blank=True, default='', max_length=600)),
                ('row_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_key', models.CharField(max_length=20, unique=True)),
                ('db_type', models.CharField(choices=[('sqlserver', 'SQL Server (on-prem / VM)'), ('azure_sql', 'Azure SQL Database'), ('azure_sql_mi', 'Azure SQL Managed Instance')], default='sqlserver', max_length=20)),
                ('server', models.CharField(default='', max_length=200)),
                ('port', models.IntegerField(default=1433)),
                ('database', models.CharField(max_length=128)),
                ('username', models.CharField(default='', max_length=128)),
                ('password', models.CharField(blank=True, default='', max_length=256)),
                ('extra_options', models.CharField(blank=True, default='', max_length=400)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['system_key'],
            },
        ),
        migrations.CreateModel(
            name='LoadRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_ts', models.DateTimeField(auto_now_add=True)),
                ('system_key', models.CharField(max_length=20)),
                ('source_table', models.CharField(max_length=128)),
                ('strategy', models.CharField(max_length=12)),
                ('rows_read', models.IntegerField(default=0)),
                ('rows_upserted', models.IntegerField(default=0)),
                ('rows_deleted', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('baseline', models.BooleanField(default=False)),
                ('committed', models.BooleanField(default=False)),
                ('status', models.CharField(default='OK', max_length=12)),
                ('note', models.CharField(blank=True, default='', max_length=600)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SystemMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_key', models.CharField(max_length=20, unique=True)),
                ('strategy', models.CharField(default='FULL', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_key', models.CharField(max_length=20)),
                ('source_table', models.CharField(max_length=128)),
                ('strategy', models.CharField(max_length=12)),
                ('ct_version', models.BigIntegerField(blank=True, null=True)),
                ('cdc_lsn', models.CharField(blank=True, max_length=40, null=True)),
                ('high_water_ts', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['system_key', 'source_table', 'strategy'],
                'unique_together': {('system_key', 'source_table', 'strategy')},
            },
        ),
    ]
